googleAnalytics = "UA-416081-1"
languageCode = "en"
defaultContentLanguage = "en"
theme = "beautifulhugo"
title = "Enrico Stahn"
canonifyurls = true
disqusShortname = "enricostahn.com"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "trac"
pygmentsUseClasses = true

[Author]
email = "enrico.stahn@gmail.com"
location = "Australia"
facebook = "stahn"
github = "estahn"
gitlab = "estahn"
instagram = "estahn"
linkedin = "enricostahn"
name = "Enrico Stahn"
reddit = "estahn"
stackoverflow = "users/38250/enrico-stahn"
twitter = "estahn"
website = "enricostahn.com"
xing = "Enrico_Stahn"

[Params]
  comments = true
  commit = false
  homeTitle = "Hi, I'm Enrico"
  logo = "/img/me.jpg"
  readingTime = true
  rss = true
  socialShare = true
  subtitle = "Software Engineer / Technology evangelist / Rock Climber"
  useHLJS = true

[Params.staticman]
api = "https://api.staticman.net/v2/entry/estahn/estahn.github.io/master/comments"
pulls = "https://github.com/estahn/estahn.github.io/pulls"

[Params.staticman.recaptcha]
secret = "hsGjWtWHR4HK4pT7cUsWTArJdZDxxE2pkdg/ArwCguqYQrhuubjj3RS9C5qa8xu4cx/Y9EwHwAMEeXPCZbLR9eW1K9LshissvNcYFfC/b8KKb4deH4V1+oqJEk/JcoK6jp6Rr2nZV4rjDP9M7nunC3WR5UGwMIYb8kKhur9pAic="
sitekey = "6LeGeTgUAAAAAAqVrfTwox1kJQFdWl-mLzKasV0v"

[[Params.bigimg]]
desc = "Blue Mountains, NSW, Australia"
src = "/img/home-bigimg.jpg"

[[menu.main]]
name = "About"
url = "/page/about/"
weight = 2

[[menu.main]]
name = "Blog"
weight = 1
