baseURL = "https://enricostahn.com/"
googleAnalytics = "UA-416081-1"
languageCode = "en-us"
theme = "codex"
title = "Enrico Stahn"
copyright = "Enrico Stahn © 2011 - {year}"
enableEmoji = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    noClasses = false
    tabWidth = 2

[params]
  author = "Enrico Stahn"
  description = "Thoughts about things."
  avatar = "avatar.jpg"
  name = "Enrico Stahn"

  twitter = "https://twitter.com/estahn"
  github = "https://github.com/estahn"
  linkedin = "https://www.linkedin.com/in/enricostahn/"
  email = "mailto:enrico.stahn@gmail.com"

[menu]
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "Posts"
  weight = 2
  url = "/post"

  #[[menu.main]]
  #name = "About"
  #url = "/page/about/"
  #weight = 2

[outputs]
home = [ "HTML", "RSS" ]
