name: publish

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: chabad360/hugo-gh-pages@v2
        with:
          githubToken: ${{ secrets.PERSONAL_TOKEN }}
